name: Publish snapshot to SciJava Maven

on: 
  workflow_dispatch:

jobs:
  jars:
    name: Build jars
    uses: ./.github/workflows/jars.yml
    
  publish:
    needs: jars

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: blosc-jars
  
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Publish snapshot
      uses: gradle/gradle-build-action@v2
      with:
        arguments: publish
      env:
        MAVEN_USER: ${{ secrets.MAVEN_USER }}
        MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
